# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel/launcher/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel/launcher/common

PRODUCT_COPY_FILES += \
    vendor/pixel/launcher/common/proprietary/product/etc/default-permissions/default-permissions_pixelweather.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/default-permissions/default-permissions_pixelweather.xml

PRODUCT_PACKAGES += \
    WeatherPixelPrebuilt_10006113 \
    NexusLauncherRelease

ifeq ($(TARGET_IS_TABLET),true)

PRODUCT_PACKAGES += \
    NexusLauncherReleaseTablet
endif
