# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel_launcher/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel_launcher/common

PRODUCT_COPY_FILES += \
    vendor/pixel_launcher/common/proprietary/system_ext/etc/default-permissions/default-permissions_pixelweather.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/default-permissions_pixelweather.xml

PRODUCT_PACKAGES += \
    WeatherPixelPrebuilt_24D1 \
    NexusLauncherRelease
