# Automatically generated file. DO NOT MODIFY
#
# This file is generated by vendor/pixel/launcher/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/pixel/launcher/common

PRODUCT_COPY_FILES += \
    vendor/pixel/launcher/common/proprietary/system_ext/etc/default-permissions/default-permissions_pixelweather.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/default-permissions/default-permissions_pixelweather.xml

PRODUCT_PACKAGES += \
    WeatherPixelPrebuilt_24D1 \
    NexusLauncherRelease

ifeq ($(USE_TABLET_BT_COD),true)

PRODUCT_PACKAGES += \
    NexusLauncherReleaseTablet
endif
